# mercadillo_runas.proc 
#       No arguments...
#           Walk all the resources

#                   proc                                          Categoria                scroll              output_path
# call_proc   recursos/mercadillos/mercadillo_selecionar_categoria                   Runa de forjamagia            0
call_proc   recursos/mercadillos/mercadillo_todos_los_items_de_categoria           Runa_de_forjamagia                          "./data/runes/impure"
