# mercadillo_mineros.proc 
#       No arguments...
#           Walk all the resources

#                   proc                                    Categoria         scroll                 output_path
call_proc   recursos/mercadillos/mercadillo_selecionar_categoria                   Aleación          0
call_proc   recursos/mercadillos/mercadillo_todos_los_items_de_categoria           Aleación                           "./data/resources/impure"
call_proc   recursos/mercadillos/mercadillo_selecionar_categoria                   Mineral           0
call_proc   recursos/mercadillos/mercadillo_todos_los_items_de_categoria           Mineral                            "./data/resources/impure"
call_proc   recursos/mercadillos/mercadillo_selecionar_categoria                   bruta             0
call_proc   recursos/mercadillos/mercadillo_todos_los_items_de_categoria           Piedra_bruta                       "./data/resources/impure"
call_proc   recursos/mercadillos/mercadillo_selecionar_categoria                   mágica            0
call_proc   recursos/mercadillos/mercadillo_todos_los_items_de_categoria           Piedra_mágica                      "./data/resources/impure"
call_proc   recursos/mercadillos/mercadillo_selecionar_categoria                   preciosa          0
call_proc   recursos/mercadillos/mercadillo_todos_los_items_de_categoria           Piedra_preciosa                    "./data/resources/impure"
