call_proc       oficios/interactuar_con_recurso     2073      1035      10          10          $1
call_proc       oficios/interactuar_con_recurso     1723      1004      10          10          $1
call_proc       oficios/interactuar_con_recurso     2065      606      10          10          $1
call_proc       oficios/interactuar_con_recurso     2001      195      10          10          $1
call_proc       oficios/interactuar_con_recurso     1365      536      10          10          $1
call_proc       oficios/interactuar_con_recurso     1220      830      10          10          $1
call_proc       oficios/interactuar_con_recurso     992      869      10          10          $1
call_proc       oficios/interactuar_con_recurso     1203      309      10          10          $1
