call_proc       oficios/interactuar_con_recurso     788      175      10          10          $1
call_proc       oficios/interactuar_con_recurso     1576      66      10          10          $1
call_proc       oficios/interactuar_con_recurso     2074      243      10          10          $1
call_proc       oficios/interactuar_con_recurso     1292      443      10          10          $1
call_proc       oficios/interactuar_con_recurso     1708      417      10          10          $1
call_proc       oficios/interactuar_con_recurso     2069      1035      10          10          $1
call_proc       oficios/interactuar_con_recurso     1781      1035      10          10          $1
call_proc       oficios/interactuar_con_recurso     1504      1035      10          10          $1
