# mercadillo_todos_los_items_de_categoria_helper_b.proc
#   Arguments:
#       $1=nombre-del-archivo, $2=carpeta-de-salida, $3=x-coord-upper_left_name, $4=y-coord-upper_left_name, $5=category

# Scroll down a little
set_prev
hold_click          1075        951         450
sleep 200
break_if_no_diff    399         336         247         625

# Process all new items
loop                25          mercadillo_todos_los_items_de_categoria_helper_a      $1      $2      $3      $4      $5