# mercadillo_pescadores_todas_las_categorias.proc 
#       No arguments...
#           Walk all the resources

#                   proc                                    Categoria             scroll                 output_path
call_proc   mercadillos/mercadillo_selecionar_categoria                   comestible            0
call_proc   mercadillos/mercadillo_todos_los_items_de_categoria           Pescado_comestible                   "./data/resources/impure"
call_proc   mercadillos/mercadillo_selecionar_categoria                   vaciado               0
call_proc   mercadillos/mercadillo_todos_los_items_de_categoria           Pescado_vaciado                      "./data/resources/impure"
call_proc   mercadillos/mercadillo_selecionar_categoria                   Pez                   0
call_proc   mercadillos/mercadillo_todos_los_items_de_categoria           Pez                                  "./data/resources/impure"
